//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace MVC_Test.Models.Core
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Album>();
                db.CreateTable<Artist>();
                db.CreateTable<Customer>();
                db.CreateTable<Employee>();
                db.CreateTable<Genre>();
                db.CreateTable<Invoice>();
                db.CreateTable<InvoiceLine>();
                db.CreateTable<MediaType>();
                db.CreateTable<Playlist>();
                db.CreateTable<PlaylistTrack>();
                db.CreateTable<Track>();
            }
        }
    }
    public partial class Album
    {
        [PrimaryKey, AutoIncrement]
        public Int64 AlbumId { get; set; }
        
        [MaxLength(160)]
        [NotNull]
        public String Title { get; set; }
        
        [Indexed(Name = "IFK_AlbumArtistId", Order = 0)]
        [NotNull]
        public Int64 ArtistId { get; set; }
        
    }
    
    public partial class Artist
    {
        [PrimaryKey, AutoIncrement]
        public Int64 ArtistId { get; set; }
        
        [MaxLength(120)]
        public String Name { get; set; }
        
    }
    
    public partial class Customer
    {
        [PrimaryKey, AutoIncrement]
        public Int64 CustomerId { get; set; }
        
        [MaxLength(40)]
        [NotNull]
        public String FirstName { get; set; }
        
        [MaxLength(20)]
        [NotNull]
        public String LastName { get; set; }
        
        [MaxLength(80)]
        public String Company { get; set; }
        
        [MaxLength(70)]
        public String Address { get; set; }
        
        [MaxLength(40)]
        public String City { get; set; }
        
        [MaxLength(40)]
        public String State { get; set; }
        
        [MaxLength(40)]
        public String Country { get; set; }
        
        [MaxLength(10)]
        public String PostalCode { get; set; }
        
        [MaxLength(24)]
        public String Phone { get; set; }
        
        [MaxLength(24)]
        public String Fax { get; set; }
        
        [MaxLength(60)]
        [NotNull]
        public String Email { get; set; }
        
        [Indexed(Name = "IFK_CustomerSupportRepId", Order = 0)]
        public Int64? SupportRepId { get; set; }
        
    }
    
    public partial class Employee
    {
        [PrimaryKey, AutoIncrement]
        public Int64 EmployeeId { get; set; }
        
        [MaxLength(20)]
        [NotNull]
        public String LastName { get; set; }
        
        [MaxLength(20)]
        [NotNull]
        public String FirstName { get; set; }
        
        [MaxLength(30)]
        public String Title { get; set; }
        
        [Indexed(Name = "IFK_EmployeeReportsTo", Order = 0)]
        public Int64? ReportsTo { get; set; }
        
        public DateTime? BirthDate { get; set; }
        
        public DateTime? HireDate { get; set; }
        
        [MaxLength(70)]
        public String Address { get; set; }
        
        [MaxLength(40)]
        public String City { get; set; }
        
        [MaxLength(40)]
        public String State { get; set; }
        
        [MaxLength(40)]
        public String Country { get; set; }
        
        [MaxLength(10)]
        public String PostalCode { get; set; }
        
        [MaxLength(24)]
        public String Phone { get; set; }
        
        [MaxLength(24)]
        public String Fax { get; set; }
        
        [MaxLength(60)]
        public String Email { get; set; }
        
    }
    
    public partial class Genre
    {
        [PrimaryKey, AutoIncrement]
        public Int64 GenreId { get; set; }
        
        [MaxLength(120)]
        public String Name { get; set; }
        
    }
    
    public partial class Invoice
    {
        [PrimaryKey, AutoIncrement]
        public Int64 InvoiceId { get; set; }
        
        [Indexed(Name = "IFK_InvoiceCustomerId", Order = 0)]
        [NotNull]
        public Int64 CustomerId { get; set; }
        
        [NotNull]
        public DateTime InvoiceDate { get; set; }
        
        [MaxLength(70)]
        public String BillingAddress { get; set; }
        
        [MaxLength(40)]
        public String BillingCity { get; set; }
        
        [MaxLength(40)]
        public String BillingState { get; set; }
        
        [MaxLength(40)]
        public String BillingCountry { get; set; }
        
        [MaxLength(10)]
        public String BillingPostalCode { get; set; }
        
        [NotNull]
        public Decimal Total { get; set; }
        
    }
    
    public partial class InvoiceLine
    {
        [PrimaryKey, AutoIncrement]
        public Int64 InvoiceLineId { get; set; }
        
        [Indexed(Name = "IFK_InvoiceLineInvoiceId", Order = 0)]
        [NotNull]
        public Int64 InvoiceId { get; set; }
        
        [Indexed(Name = "IFK_InvoiceLineTrackId", Order = 0)]
        [NotNull]
        public Int64 TrackId { get; set; }
        
        [NotNull]
        public Decimal UnitPrice { get; set; }
        
        [NotNull]
        public Int64 Quantity { get; set; }
        
    }
    
    public partial class MediaType
    {
        [PrimaryKey, AutoIncrement]
        public Int64 MediaTypeId { get; set; }
        
        [MaxLength(120)]
        public String Name { get; set; }
        
    }
    
    public partial class Playlist
    {
        [PrimaryKey, AutoIncrement]
        public Int64 PlaylistId { get; set; }
        
        [MaxLength(120)]
        public String Name { get; set; }
        
    }
    
    public partial class PlaylistTrack
    {
        [NotNull]
        public Int64 PlaylistId { get; set; }
        
        [Indexed(Name = "IFK_PlaylistTrackTrackId", Order = 0)]
        [NotNull]
        public Int64 TrackId { get; set; }
        
    }
    
    public partial class Track
    {
        [PrimaryKey, AutoIncrement]
        public Int64 TrackId { get; set; }
        
        [MaxLength(200)]
        [NotNull]
        public String Name { get; set; }
        
        [Indexed(Name = "IFK_TrackAlbumId", Order = 0)]
        public Int64? AlbumId { get; set; }
        
        [Indexed(Name = "IFK_TrackMediaTypeId", Order = 0)]
        [NotNull]
        public Int64 MediaTypeId { get; set; }
        
        [Indexed(Name = "IFK_TrackGenreId", Order = 0)]
        public Int64? GenreId { get; set; }
        
        [MaxLength(220)]
        public String Composer { get; set; }
        
        [NotNull]
        public Int64 Milliseconds { get; set; }
        
        public Int64? Bytes { get; set; }
        
        [NotNull]
        public Decimal UnitPrice { get; set; }
        
    }
    
}
